name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Android
        uses: android-actions/setup-android@v3

      - name: Instalar Android SDK
        run: sdkmanager "platforms;android-35" "build-tools;35.0.0" "platform-tools"

      - name: Descomprimir proyecto
        run: |
          ZIP_FILE=$(find . -maxdepth 1 -name "*.zip" | head -n 1)
          echo "Usando: $ZIP_FILE"
          unzip -q "$ZIP_FILE"

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - name: Compilar APK
        run: |
          cd nomina_cfe_android
          gradle :app:assembleDebug

      - name: Preparar APK
        run: |
          cp nomina_cfe_android/app/build/outputs/apk/debug/app-debug.apk Revisor-Nomina-CFE-2026.apk

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: Revisor-Nomina-CFE-2026
          path: Revisor-Nomina-CFE-2026.apk
